### ISSUE TITLE
Support GitHub merge queues

### ISSUE THREAD

**Issue by smailc** [gruntwork-io/pipelines-dispatch#46]
We have tried to implement GitHub merge queues to ensure rebasing of code prior to merge and smooth merging of multiple branches. We are finding that pipelines-dispatch is failing as the build is using a special merge queue branch. This means that the following env call is empty:

PR_NUMBER: ${{ github.event.number }}

So calling the pipelines dispatch is giving this error:

PR_NUMBER: 
  
accepts 1 arg(s), received 0
Error: Process completed with exit code 1.

Is it in the roadmap to support GitHub merge queues?

**Comment by ZachGoldberg** [comment]
Hi @smailc  - Unfortunately we do not plan to support Merge Queues with pipelines-dispatch.  Pipelines-dispatch is actually officially a deprecated module now in favor of the [updated pipelines architecture](https://docs.gruntwork.io/infrastructure-pipelines/overview/deprecation) which obviate the issues caused by not having an event number.  I believe we're gearing up to have a conversation with your company in the coming weeks about planning an upgrade.
